### ISSUE TITLE
load_entry_point('hy==0.13.0', 'console_scripts', 'hy')()

### ISSUE THREAD

**Issue by POMXARK** [philiparvidsson/LSTM-Text-Generation#1]
initializing...
Using TensorFlow backend.
loading sources...
Traceback (most recent call last):
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/bin/hy", line 11, in 
load_entry_point('hy==0.13.0', 'console_scripts', 'hy')()
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/lib/python3.5/site-packages/hy/cmdline.py", line 344, in hy_main
sys.exit(cmdline_handler("hy", sys.argv))
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/lib/python3.5/site-packages/hy/cmdline.py", line 332, in cmdline_handler
return run_file(options.args[0])
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/lib/python3.5/site-packages/hy/cmdline.py", line 211, in run_file
pretty_error(import_file_to_module, "main", filename)
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/lib/python3.5/site-packages/hy/cmdline.py", line 184, in pretty_error
return func(*args, **kw)
File "/home/viewadmin/anaconda3/envs/lstm_shakespeare_3.5.0/lib/python3.5/site-packages/hy/importer.py", line 87, in import_file_to_module
load_module(module_name))
File "", line 385, in _check_name_wrapper
File "", line 806, in load_module
File "", line 665, in load_module
File "", line 265, in _load_module_shim
File "", line 626, in _exec
File "", line 662, in exec_module
File "", line 222, in _call_with_frames_removed
File "./lstm.hy", line 232, in 
(defmain [&rest args]
File "./lstm.hy", line 1815, in _hy_anon_fn_19
File "./lstm.hy", line 88, in load_all_sources
(list-comp (load-source s) [s sources]))
TypeError: 'NoneType' object is not iterable
(lstm_shakespeare_3.5.0) viewadmin@ubuntu:~/LSTM-Text-Generation$

P.S WHYYYYYYYYYYY???? puthon3.5.4 ubunty 16.04. PLEES HELP MY

**Comment by mark-watson** [comment]
Where is "dict-comp " defined?

**Comment by philiparvidsson** [comment]
@mark-watson it seems to have been removed from the language!
