### ISSUE TITLE
hy.errors.HySyntaxError: Can't assign or delete a Expression

### ISSUE THREAD

**Issue by Qiangong2** [philiparvidsson/LSTM-Text-Generation#5]
I don't know if you're still working on this, but I receive the following when trying to run `lstm.hy`:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 290, in run_path
  File "/root/LSTM-Text-Generation/lstm.hy", line 49
    (for [(, j xc) (enumerate s)]
          ^
hy.errors.HySyntaxError: Can't assign or delete a Expression
```

**Comment by philiparvidsson** [comment]
Hey man, thanks for the interest. Hy is an awesome language - but I suspect much has happened since I wrote this (I was onboarded early in hy's development), so the language has probably changed to a point where my original source coesn't work anymore!
